version: '3.9'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=crud
      - MYSQL_USER=crud
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./app/db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
      - ./my-datavolume:/var/lib/mysql
     
  blog_app:
    build:						
      context: ./
      dockerfile: Dockerfile
    #volumes:
    #  - "/. :/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
      #- 443:443 # for future ssl traffic
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    